$ ! buid script
$ SET DEF DISK$USERS:[RDOYLE.C]
$ CC/LIST/DEBUG=(SYMBOLS,TRACEBACK)/NOOPTIMIZE DISK$USERS:[RDOYLE.C]POINTER.C
$ LINK/MAP/DEBUG/EXECUTABLE=DISK$USERS:[RDOYLE.C]POINTER.EXE DISK$USERS:[RDOYLE.C]POINTER.OBJ 
